### ISSUE TITLE
No SSE event received when removing a location (room)

### ISSUE THREAD

**Issue by RicArch97** [crownstone/crownstone-lib-nodejs-sse#3]
Steps taken:
* Added a new room in the Crownstone app (SSE event received for that)
* Synced the app with the cloud to let it update
* Waited a bit, then removed the room again in the app (no Crownstones were added to it)

Events were monitored on https://events.crownstone.rocks/

**Comment by AlexDM0** [comment]
Thanks for the report! I found the issue and fixed it.

Regards
